"""
Compile lesson source (lessons/unit*.md, English only) into data/lessons.json.

    python -X utf8 pipeline/build_lessons.py

Source format: "## L<unit>.<n> Title", optional "unlocks: id, id" line, then paragraphs.
Corpus references: {Gen.1.3#1} word 1 of the verse (Hebrew numbering, read tokens, 1-based);
{Gen.1.3#1-2} a phrase; {Gen.1.3#1/0} highlight morpheme 0. The compiler resolves each to OSHB
token ids and copies the Hebrew from data/text, so lessons never contain typed Hebrew. A
transliteration typed right after a reference (an authoring aid) must match the generated one
and is dropped from the output.

Output: {"lessons": [{id, unit, title, unlocks, body, refs}], "toks": {id: snapshot}}.
body keeps "{n}" placeholders indexing refs; refs[n] = {"ids": [...], "hl": part or null}.
"""
import glob
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "lessons")
TEXT = os.path.join(ROOT, "data", "text")
OUT = os.path.join(ROOT, "data", "lessons.json")
REF = re.compile(r"\{(\w+)\.(\d+)\.(\d+)#(\d+)(?:-(\d+))?(?:/(\d+))?\}( [^\s,.;:\"(]+(?: [^\s,.;:\"(]+)*)?")
HEBREW = re.compile("[%s-%s]" % (chr(0x591), chr(0x5F4)))
MAX_WORDS = 150


def chapter(book, ch, cache={}):
    key = (book, ch)
    if key not in cache:
        path = os.path.join(TEXT, book, f"{ch}.json")
        cache[key] = json.load(open(path, encoding="utf-8")) if os.path.exists(path) else None
    return cache[key]


def parse(path):
    text = open(path, encoding="utf-8").read()
    if HEBREW.search(text):
        raise SystemExit(f"{path}: Hebrew characters in lesson source")
    unit = int(re.search(r"unit(\d+)\.md$", path)[1])
    lessons = []
    for block in re.split(r"^## ", text, flags=re.M)[1:]:
        head, _, rest = block.partition("\n")
        m = re.match(r"(L\d+\.\d+)\s+(.*)", head.strip())
        if not m:
            raise SystemExit(f"{path}: bad heading {head!r}")
        unlocks = []
        um = re.match(r"unlocks:\s*(.*)\n", rest)
        if um:
            unlocks = [u.strip() for u in um[1].split(",") if u.strip()]
            rest = rest[um.end():]
        lessons.append({"id": m[1], "unit": unit, "title": m[2].strip(), "unlocks": unlocks,
                        "body": re.sub(r"\n{3,}", "\n\n", rest).strip()})
    return lessons


def resolve(lesson, toks, errors):
    refs = []

    def sub(m):
        book, ch, v, a, z, hl, typed = m.groups()
        c = chapter(book, int(ch))
        verse = next((x for x in c["verses"] if x["v"] == int(v)), None) if c else None
        a, z = int(a), int(z or a)
        if verse is None or z > len(verse["tokens"]) or a < 1:
            errors.append(f"{lesson['id']}: {m[0]} does not resolve")
            return m[0]
        ts = verse["tokens"][a - 1:z]
        if hl is not None and int(hl) >= len(ts[0]["p"]):
            errors.append(f"{lesson['id']}: {m[0]} has no morpheme {hl}")
        for t in ts:
            toks[t["id"]] = {k: t[k] for k in ("id", "s", "tr", "g", "gs", "gr", "p")}
            toks[t["id"]]["ref"] = f"{book}.{ch}.{v}"
        refs.append({"ids": [t["id"] for t in ts], "hl": int(hl) if hl is not None else None})
        out = "{%d}" % (len(refs) - 1)
        if typed:                       # authoring aid: must equal the generated translit; dropped
            gen = " ".join(t["tr"] for t in ts)
            words = typed.split()
            if " ".join(words[:len(gen.split())]) != gen:
                errors.append(f"{lesson['id']}: {m[0].strip()} typed {typed.strip()!r}, corpus gives {gen!r}")
            rest = words[len(gen.split()):]
            out += (" " + " ".join(rest)) if rest else ""
        return out

    lesson["body"] = REF.sub(sub, lesson["body"])
    lesson["refs"] = refs
    words = len(re.sub(r"\{\d+\}", "", lesson["body"]).split())
    if words > MAX_WORDS:
        errors.append(f"{lesson['id']}: {words} words (max {MAX_WORDS})")
    lesson["words"] = words


def main():
    lessons, toks, errors = [], {}, []
    for path in sorted(glob.glob(os.path.join(SRC, "unit*.md")), key=lambda p: int(re.search(r"(\d+)\.md$", p)[1])):
        for les in parse(path):
            resolve(les, toks, errors)
            lessons.append(les)
    if errors:
        print("\n".join(errors))
        sys.exit(1)
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump({"_note": "Generated by pipeline/build_lessons.py from lessons/*.md.",
                   "lessons": lessons, "toks": toks}, f, ensure_ascii=False, indent=1)
    print(f"{len(lessons)} lessons, {len(toks)} tokens; words max {max(l['words'] for l in lessons)}")


if __name__ == "__main__":
    main()
