"""
Phase 2 measurements (SPEC Appendix A: M1-M11, M13) over the narrative corpus.

    python -X utf8 pipeline/measure.py

Writes
  data/measures/*.json        full tables (ranked lemmas, verb forms, reading pools, ...)
  data/parse_quarantine.json  M13: tokens whose OSHB parse BHSA contradicts
  MEASURES.md                 report; text above the GENERATED marker is kept, the rest rewritten

Corpus = read, non-poem, Hebrew tokens of corpus_config.json. Morpheme classes (M1):
  suffix  morph S*            prefix  one-letter lemma (c d b l k m i s)
  name    morph Np / Ng       vocab   everything else with a lemma (ranked)
Coverage (a) lemma: ranked vocab morphemes with rank <= N / all vocab morphemes.
Coverage (b) word: tokens whose vocab morphemes all have rank <= N / all tokens; names,
prefixes and suffixes count as known (they are taught in their own tracks).
"""
import collections
import json
import os
import re
import statistics
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import align_bhsa  # noqa: E402
import corpus  # noqa: E402
import translit  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "data", "measures")
QUAR = os.path.join(ROOT, "data", "parse_quarantine.json")
MD = os.path.join(ROOT, "MEASURES.md")
TBESH = os.path.join(ROOT, "sources", "stepbible", "Lexicons",
                     "TBESH - Translators Brief lexicon of Extended Strongs for Hebrew - STEPBible.org CC BY.txt")
MARKER = "<!-- GENERATED by pipeline/measure.py below this line; edit above it only -->"

RANKS = [50, 120, 190, 260, 330, 400, 480, 570, 660, 750, 1000, 1500, 2000]
PASSAGE_RANKS = [330, 400, 480, 570, 660, 750]
CORE = 750
KINGS = {"0591", "0592", "0593", "0594", "0595", "0596"}          # atnach .. tifcha (levels 1-2)
DUKES = {"0597", "0598", "0599", "059a", "059b", "05ae"}          # revia, zarqa, pashta, yetiv, tevir
STRIP = re.compile("[%s-%s%s]" % (chr(0x591), chr(0x5AF), chr(0x5BD)))  # accents + meteg

STEM = {"q": "Qal", "N": "Niphal", "p": "Piel", "P": "Pual", "h": "Hiphil", "H": "Hophal",
        "t": "Hithpael", "o": "Polel", "O": "Polal", "r": "Hithpolel", "m": "Poel", "M": "Poal",
        "k": "Palel", "K": "Pulal", "Q": "Qal passive", "l": "Pilpel", "L": "Polpal",
        "f": "Hithpalpel", "D": "Nithpael", "j": "Pealal", "i": "Pilel", "u": "Hothpaal",
        "c": "Tiphil", "v": "Hishtaphel", "w": "Nithpalel", "y": "Nithpoel", "z": "Hithpoel"}
CONJ = {"p": "qatal", "q": "weqatal", "i": "yiqtol", "j": "jussive", "h": "cohortative",
        "w": "wayyiqtol", "v": "imperative", "r": "participle", "s": "pass. participle",
        "a": "inf. abs.", "c": "inf. cstr."}
FAMILY = {"w": "wayyiqtol", "p": "qatal/weqatal", "q": "qatal/weqatal", "i": "yiqtol/volitive",
          "j": "yiqtol/volitive", "h": "yiqtol/volitive", "v": "yiqtol/volitive",
          "r": "participle", "s": "participle", "a": "infinitive", "c": "infinitive"}
FINITE = set("pqijhwv")
# BHSA equivalents for M13
BH_STEM = {"q": {"qal"}, "N": {"nif"}, "p": {"piel"}, "P": {"pual"}, "h": {"hif"}, "H": {"hof"},
           "t": {"hit"}, "v": {"hsht"}, "o": {"poel", "piel"}, "O": {"poal", "pual"},
           "r": {"htpo", "hit"}, "m": {"poel"}, "M": {"poal"}, "l": {"piel"}, "L": {"pual"},
           "f": {"hit"}, "k": {"piel"}, "K": {"pual"}, "Q": {"pasq", "qal"}, "D": {"nit"},
           "u": {"hotp"}, "c": {"tif"}, "i": {"piel"}, "j": {"piel"}, "y": {"nit"},
           "z": {"htpo"}, "w": {"nit"}}
BH_CONJ = {"p": "perf", "q": "perf", "i": "impf", "j": "impf", "h": "impf", "w": "wayq",
           "v": "impv", "r": "ptca", "s": "ptcp", "a": "infa", "c": "infc"}
BH_PS = {"1": "p1", "2": "p2", "3": "p3"}
BH_NU = {"s": "sg", "p": "pl", "d": "du"}
# Spec passages (M11), Hebrew versification
PASSAGES = [("Jonah 1", "Jonah", (1, 1), (1, 16)), ("Jonah 2 (prose)", "Jonah", (2, 1), (2, 11)),
            ("Jonah 3", "Jonah", (3, 1), (3, 10)), ("Jonah 4", "Jonah", (4, 1), (4, 11)),
            ("Ruth 1", "Ruth", (1, 1), (1, 22)), ("Ruth 2", "Ruth", (2, 1), (2, 23)),
            ("Ruth 3", "Ruth", (3, 1), (3, 18)), ("Ruth 4", "Ruth", (4, 1), (4, 22)),
            ("Gen 1:1-2:3", "Gen", (1, 1), (2, 3)), ("Gen 12:1-9", "Gen", (12, 1), (12, 9)),
            ("Gen 22:1-19", "Gen", (22, 1), (22, 19)), ("Gen 37", "Gen", (37, 1), (37, 36)),
            ("Exod 1", "Exod", (1, 1), (1, 22)), ("Exod 2", "Exod", (2, 1), (2, 25)),
            ("Exod 3 (target)", "Exod", (3, 1), (3, 22)), ("Exod 14 (target)", "Exod", (14, 1), (14, 31))]
# Short verse-poems inside the prose books that the current poem list keeps (SPEC 0.1 asks for
# others found). Candidates only; nothing here is excluded until Lane decides.
POEM_CANDIDATES = [("Gen", 2, 23, 2, 23), ("Gen", 4, 23, 4, 24), ("Gen", 9, 25, 9, 27),
                   ("Gen", 16, 11, 16, 12), ("Gen", 24, 60, 24, 60), ("Gen", 25, 23, 25, 23),
                   ("Gen", 27, 27, 27, 29), ("Gen", 27, 39, 27, 40), ("Exod", 15, 21, 15, 21),
                   ("Num", 6, 24, 6, 26), ("Num", 10, 35, 10, 36), ("Num", 21, 14, 21, 15),
                   ("Num", 21, 17, 21, 18), ("Num", 21, 27, 21, 30), ("Josh", 10, 12, 10, 13),
                   ("Judg", 14, 14, 14, 14), ("Judg", 14, 18, 14, 18), ("Judg", 15, 16, 15, 16),
                   ("1Sam", 15, 22, 15, 23), ("1Sam", 18, 7, 18, 7),
                   ("2Sam", 3, 33, 3, 34), ("1Kgs", 8, 12, 8, 13)]


# --- helpers -------------------------------------------------------------------------------

def pclass(p):
    m, lem = p["morph"], p["lemma"]
    if m[:1] == "S":
        return "suffix"
    if lem.isalpha():
        return "prefix"
    if m[:2] in ("Np", "Ng"):
        return "name"
    if not lem:
        return "nolemma"
    return "vocab"


def lkey(lem):
    m = re.match(r"(\d+)\s*([a-z]?)", lem)
    return (int(m[1]), m[2], lem) if m else (10 ** 9, "", lem)


def vpart(t):
    return next((p for p in t["parts"] if p["morph"][:1] == "V"), None)


def fkey(t):
    return (STRIP.sub("", t["surface"]), t["lemma"], t["morph"])


def pct(x):
    return f"{100 * x:.1f}%"


def table(head, rows):
    out = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return out


def in_span(t, book, a, z):
    return t["book"] == book and a <= (t["ch"], t["v"]) <= z


def parse_label(morph, lemma_gloss=""):
    """'HC/Vqw3ms' -> 'Qal wayyiqtol 3ms'."""
    v = next((m for m in morph[1:].split("/") if m[:1] == "V"), "")
    if not v:
        return morph
    rest = v[3:]
    if v[2] in "rs":
        rest = rest[:2]
    lab = f"{STEM.get(v[1], v[1])} {CONJ.get(v[2], v[2])} {rest}".strip()
    pre = [m for m in morph[1:].split("/") if m[:1] in "CR"]
    suf = [m for m in morph[1:].split("/") if m[:1] == "S"]
    if pre:
        lab = "+".join("w" if m == "C" else "prep" for m in pre) + " " + lab
    for m in suf:
        lab += {"Sd": " +dir. he", "Sh": " +par. he", "Sn": " +par. nun"}.get(m[:2], " +sfx " + m[2:])
    return lab + (f" ({lemma_gloss})" if lemma_gloss else "")


def load_tbesh():
    out = {}
    with open(TBESH, encoding="utf-8") as f:
        for line in f:
            c = line.rstrip("\n").split("\t")
            m = re.match(r"H0*(\d+)([a-zA-Z]?)$", c[0])
            if not m or len(c) < 7:
                continue
            key = m[1] + (" " + m[2].lower() if m[2] else "")
            out.setdefault(key, (c[3], c[6].strip()))
            out.setdefault(m[1] + "*", (c[3], c[6].strip()))
    return out


def weak_class(lex):
    """ETCBC lex (e.g. 'QWM[') -> primary weak class of the root."""
    r = re.sub(r"[^A-Z<>]", "", lex or "")
    if len(r) != 3:
        return "other"
    a, b, c = r
    if c == "H":
        return "III-he"
    if b in "WJ":
        return "hollow"
    if a == "N":
        return "I-nun"
    if a in "JW":
        return "I-yod/waw"
    if a == ">":
        return "I-alef"
    if c == ">":
        return "III-alef"
    if b == c:
        return "geminate"
    if set(r) & set("><HX"):
        return "guttural"
    return "strong"


# --- the run -------------------------------------------------------------------------------

class Run:
    def __init__(self):
        t0 = time.time()
        self.all = list(corpus.load_tokens())
        books = corpus.load_config()["books"]
        self.pm, self.split = align_bhsa.align(self.all, books)
        self.F = align_bhsa.load_features()
        self.toks = [t for t in self.all if t["read"] and not t["poem"] and t["lang"] == "H"]
        self.stable = translit.build_stress_table(self.all)
        self.tb = load_tbesh()
        self.md = []
        self.timing = {"load+align": time.time() - t0}

    # display
    def tr(self, t):
        return translit.translit_token(t, self.stable)["text"]

    def phrase(self, ts):
        return " ".join(self.tr(t) + ("-" if t["maqqef_next"] else "") for t in ts).replace("- ", "-")

    def gloss(self, lem):
        g = self.tb.get(lem) or self.tb.get(re.sub(r"\D.*", "", lem) + "*")
        return g[1] if g else ""

    def lemma_label(self, lem):
        g = self.tb.get(lem) or self.tb.get(re.sub(r"\D.*", "", lem) + "*") or ("", "")
        t = self.label_tok.get(lem)
        x = self.tr(t) if t else lem
        return f"{x} '{g[1]}'"

    # M1
    def m1(self):
        cls, cnt, names, pos = collections.Counter(), collections.Counter(), collections.Counter(), {}
        for t in self.toks:
            for p in t["parts"]:
                c = pclass(p)
                cls[c] += 1
                if c == "vocab":
                    cnt[p["lemma"]] += 1
                    pos.setdefault(p["lemma"], collections.Counter())[p["morph"][:2] if p["morph"][:1] in "NAPTV" else p["morph"][:1]] += 1
                elif c == "name":
                    names[p["lemma"]] += 1
        # label token per lemma: a bare corpus word (no prefix/suffix), qatal 3ms for verbs,
        # absolute singular for nouns, else the most frequent bare spelling
        cand = collections.defaultdict(collections.Counter)
        ex = {}
        for t in self.toks:
            if len(t["parts"]) != 1 or pclass(t["parts"][0]) not in ("vocab", "name"):
                continue
            m = t["parts"][0]["morph"]
            prio = 0 if m == "Vqp3ms" else 1 if re.fullmatch(r"V.p3ms", m) else 2 if (m[:1] in "NA" and m[-2:] in ("sa",)) or m[:1] not in "VNA" else 3
            k = (prio, translit.stress_key(t["surface"]))
            cand[t["lemma"]][k] += 1
            ex.setdefault((t["lemma"], k), t)
        self.label_tok = {lem: ex[(lem, min(c, key=lambda k: (k[0], -c[k])))] for lem, c in cand.items()}
        order = sorted(cnt, key=lambda x: (-cnt[x], lkey(x)))
        self.rank = {x: i + 1 for i, x in enumerate(order)}
        self.cnt = cnt
        self.names = names
        self.lemma_rows = [{"lemma": x, "rank": i + 1, "count": cnt[x], "pos": pos[x].most_common(1)[0][0],
                            "gloss_hint": self.gloss(x)} for i, x in enumerate(order)]
        name_order = sorted(names, key=lambda x: (-names[x], lkey(x)))
        self.name_rows = [{"lemma": x, "count": names[x], "gloss_hint": self.gloss(x)} for x in name_order]
        total_parts = sum(cls.values())
        self.cls = cls
        L = self.md
        L += ["## M1. Ranked lemma list", "",
              f"Corpus: {len(self.toks):,} word tokens, {total_parts:,} morphemes. "
              f"{len(order):,} ranked lemmas; {len(names):,} name lemmas.", ""]
        L += table(["Morpheme class", "Morphemes", "Share"],
                   [(k, f"{cls[k]:,}", pct(cls[k] / total_parts)) for k in ("vocab", "prefix", "suffix", "name", "nolemma")])
        bands = [(100, None), (50, None), (20, None), (10, None), (5, None), (2, None), (1, None)]
        L += ["", "Lemmas by corpus count:", ""]
        L += table(["Count >=", "Lemmas"], [(b, sum(1 for x in order if cnt[x] >= b)) for b, _ in bands])
        L += ["", "Top 50 (glosses are TBESH hints, unreviewed):", ""]
        L += table(["Rank", "Lemma", "Count"],
                   [(r["rank"], self.lemma_label(r["lemma"]), r["count"]) for r in self.lemma_rows[:50]])
        L += ["", f"Top 50 names (names track budget is 50; {sum(names.values()):,} name tokens):", ""]
        L += table(["#", "Name", "Count"],
                   [(i + 1, self.lemma_label(r["lemma"]), r["count"]) for i, r in enumerate(self.name_rows[:50])])
        L += ["", f"Names at rank 50 cover {pct(sum(r['count'] for r in self.name_rows[:50]) / max(1, sum(names.values())))} of name tokens.", ""]

    # coverage
    def prep_cov(self):
        for t in self.toks:
            rs = [self.rank[p["lemma"]] for p in t["parts"] if pclass(p) == "vocab"]
            t["_r"] = rs
            t["_max"] = max(rs) if rs else 0
            t["_name"] = any(pclass(p) == "name" for p in t["parts"])

    @staticmethod
    def lemma_cov(ts, n):
        tot = sum(len(t["_r"]) for t in ts)
        return sum(1 for t in ts for r in t["_r"] if r <= n) / tot if tot else 1.0

    @staticmethod
    def word_cov(ts, n, names_known=True):
        return sum(1 for t in ts if t["_max"] <= n and (names_known or not t["_name"])) / len(ts)

    def m2(self):
        rows, js = [], []
        for n in RANKS:
            a, b, b2 = self.lemma_cov(self.toks, n), self.word_cov(self.toks, n), self.word_cov(self.toks, n, False)
            minc = self.lemma_rows[n - 1]["count"] if n <= len(self.lemma_rows) else 0
            rows.append((n, pct(a), pct(b), pct(b2), minc))
            js.append({"rank": n, "lemma": a, "word": b, "word_names_unknown": b2, "count_at_rank": minc})
        need = {}
        tot = sum(self.cnt.values())
        acc = 0
        for r in self.lemma_rows:
            acc += r["count"]
            for goal in (0.8, 0.9, 0.95, 0.98):
                if goal not in need and acc / tot >= goal:
                    need[goal] = r["rank"]
        self.summary["M2"] = {"rows": js, "rank_for_lemma_coverage": {str(k): v for k, v in need.items()}}
        L = self.md
        L += ["## M2. Corpus coverage by rank", ""]
        L += table(["Rank", "(a) lemma", "(b) word", "(b) names unknown", "Count at rank"], rows)
        L += ["", "Ranks needed for lemma coverage (a): " +
              ", ".join(f"{int(k * 100)}% at {v}" for k, v in need.items()) +
              ". Lane's earlier figure was about 600 lemmas for 80% (other corpus).", ""]

    def m3(self):
        L = self.md
        L += ["## M3. Exodus 3 and 14 coverage", ""]
        heads, rows = ["Rank"], {n: [n] for n in RANKS}
        info = []
        self.summary["M3"] = {}
        for ch in (3, 14):
            ts = [t for t in self.toks if t["book"] == "Exod" and t["ch"] == ch]
            heads += [f"Exod {ch} (a)", f"Exod {ch} (b)"]
            res = []
            for n in RANKS:
                a, b = self.lemma_cov(ts, n), self.word_cov(ts, n)
                rows[n] += [pct(a), pct(b)]
                res.append({"rank": n, "lemma": a, "word": b})
            lem = {p["lemma"] for t in ts for p in t["parts"] if pclass(p) == "vocab"}
            nm = {p["lemma"] for t in ts for p in t["parts"] if pclass(p) == "name"}
            vm = sum(len(t["_r"]) for t in ts)
            info.append(f"Exod {ch}: {len(ts)} tokens, {vm} vocab morphemes, {len(lem)} distinct lemmas, "
                        f"{len(nm)} distinct names.")
            self.summary["M3"][f"Exod {ch}"] = {"tokens": len(ts), "vocab_morphemes": vm,
                                                "distinct_lemmas": len(lem), "distinct_names": len(nm), "rows": res}
        L += info + [""] + table(heads, list(rows.values())) + [""]

    # M13 (before M6 so examples avoid quarantined tokens)
    def m13(self):
        F = self.F
        lexmap = collections.defaultdict(collections.Counter)
        for t in self.toks:
            for p, n in zip(t["parts"], self.pm[t["id"]]):
                if n and pclass(p) in ("vocab", "name"):
                    lexmap[p["lemma"]][F["lex"][n]] += 1
        self.lex = {k: v.most_common(1)[0][0] for k, v in lexmap.items()}
        reasons = collections.defaultdict(list)
        unchecked = []
        info = collections.Counter()
        for t in self.toks:
            tid = t["id"]
            if t["ketiv"]:
                unchecked.append(tid)
                continue
            if tid in self.split:
                if vpart(t):
                    reasons[tid].append("segmentation")
                else:
                    info["segmentation, non-verb (mostly name compounds; informational)"] += 1
            for p, n in zip(t["parts"], self.pm[tid]):
                if n is None:
                    continue
                m, c, sp = p["morph"], pclass(p), F["sp"][n]
                if m[:1] == "V":
                    if sp != "verb":
                        reasons[tid].append(f"verb-pos:{sp}")
                        continue
                    if F["vs"][n] not in BH_STEM.get(m[1], set()):
                        reasons[tid].append(f"stem:{STEM.get(m[1], m[1])}/{F['vs'][n]}")
                    if BH_CONJ.get(m[2]) != F["vt"][n]:
                        reasons[tid].append(f"conj:{CONJ.get(m[2], m[2])}/{F['vt'][n]}")
                    if m[2] in FINITE:
                        ps, g, nu = m[3:4], m[4:5], m[5:6]
                    elif m[2] in "rs":
                        ps, g, nu = "", m[3:4], m[4:5]
                    else:
                        ps, g, nu = "", "", ""
                    if ps in BH_PS and F["ps"][n] in ("p1", "p2", "p3") and BH_PS[ps] != F["ps"][n]:
                        reasons[tid].append("person")
                    if g in ("m", "f") and F["gn"][n] in ("m", "f") and g != F["gn"][n]:
                        reasons[tid].append("gender")
                    if nu in BH_NU and F["nu"][n] in ("sg", "pl", "du") and BH_NU[nu] != F["nu"][n]:
                        reasons[tid].append("number")
                    if self.lex.get(p["lemma"]) != F["lex"][n]:
                        reasons[tid].append("verb-lemma")
                elif c in ("vocab", "name"):
                    if sp == "verb":
                        reasons[tid].append(f"pos-is-verb:{m[:2]}")
                    elif m[:1] in "NA" and len(m) >= 5:
                        g, nu, st = m[2], m[3], m[4]
                        if nu in BH_NU and F["nu"][n] in ("sg", "pl", "du") and BH_NU[nu] != F["nu"][n]:
                            reasons[tid].append("noun-number")
                        if st in "ac" and F["st"][n] in ("a", "c") and st != F["st"][n]:
                            sfx = any(q["morph"][:1] == "S" for q in t["parts"])
                            info["noun-state, " + ("suffixed" if sfx else "unsuffixed") + " (informational)"] += 1
                        if g in ("m", "f") and F["gn"][n] in ("m", "f") and g != F["gn"][n]:
                            info["noun-gender (informational)"] += 1
                    if self.lex.get(p["lemma"]) != F["lex"][n]:
                        info["non-verb lemma->lex minority (informational)"] += 1
                elif m[:2] == "Sp" and len(m) >= 5:
                    bps, bgn, bnu = F["prs_ps"].get(n), F["prs_gn"].get(n), F["prs_nu"].get(n)
                    if bps in (None, "NA", "absent"):
                        reasons[tid].append("suffix-missing")
                        continue
                    if (m[2] in BH_PS and bps in ("p1", "p2", "p3") and BH_PS[m[2]] != bps) or \
                       (m[3] in ("m", "f") and bgn in ("m", "f") and m[3] != bgn) or \
                       (m[4] in BH_NU and bnu in ("sg", "pl", "du") and BH_NU[m[4]] != bnu):
                        reasons[tid].append("suffix-pgn")
        byid = {t["id"]: t for t in self.toks}
        rows = []
        for tid, rs in reasons.items():
            t = byid[tid]
            v = next((n for p, n in zip(t["parts"], self.pm[tid]) if n and p["morph"][:1] in "VN"), None)
            if v is None:
                v = next((n for n in self.pm[tid] if n), None)
            rows.append({"id": tid, "ref": t["ref"], "translit": self.tr(t), "reasons": sorted(set(rs)),
                         "oshb": {"lemma": t["lemma"], "morph": t["morph"]},
                         "bhsa": {f: F[f].get(v) for f in ("lex", "sp", "vs", "vt", "ps", "gn", "nu", "st")} if v else None})
        rows.sort(key=lambda r: (r["ref"].split(".")[0], int(r["ref"].split(".")[1]), int(r["ref"].split(".")[2])))
        kinds = collections.Counter(r.split(":")[0] for x in rows for r in x["reasons"])
        detail = collections.Counter(r for x in rows for r in x["reasons"])
        verbish = {"segmentation", "verb-pos", "stem", "conj", "person", "gender", "number", "verb-lemma", "pos-is-verb"}
        self.verb_quarantined = {x["id"] for x in rows if {r.split(":")[0] for r in x["reasons"]} & verbish}
        self.quarantined = {x["id"] for x in rows}
        self.quarantine = {"_note": "Generated by pipeline/measure.py (M13). OSHB tokens whose parse BHSA "
                           "contradicts. Parse items (verb forms, reverse parse, morpheme items) skip "
                           "these ids. 'unchecked_qere' lists qere tokens BHSA cannot be compared on.",
                           "counts": dict(kinds), "detail": dict(detail.most_common()),
                           "informational": dict(info), "unchecked_qere": unchecked, "tokens": rows}
        self.summary["M13"] = {"tokens": len(rows), "counts": dict(kinds), "unchecked_qere": len(unchecked),
                               "informational": dict(info)}
        L = self.md
        L += ["## M13. OSHB vs BHSA parse disagreements", "",
              f"Aligned by consonant position (identical streams). {len(rows):,} tokens disagree "
              f"({pct(len(rows) / len(self.toks))} of the corpus); {len(self.verb_quarantined):,} of them on a "
              f"verb or segmentation facet. {len(unchecked)} qere tokens are unchecked (BHSA describes the "
              "ketiv). Full list: `data/parse_quarantine.json`.", ""]
        L += table(["Reason", "Tokens"], [(k, v) for k, v in kinds.most_common()])
        L += ["", "Most common detailed reasons (OSHB/BHSA):", ""]
        L += table(["Detail", "Tokens"], detail.most_common(25))
        L += ["", "Not quarantined (convention differences, counted only): " +
              "; ".join(f"{k} {v:,}" for k, v in info.items()), ""]
        samples = collections.defaultdict(list)
        for x in rows:
            for r in x["reasons"]:
                k = r.split(":")[0]
                if len(samples[k]) < 4:
                    samples[k].append(x)
        L += ["Samples per reason:", ""]
        srows = []
        for k, xs in samples.items():
            for x in xs:
                b = x["bhsa"] or {}
                srows.append((k, x["ref"], x["translit"], x["oshb"]["morph"], x["oshb"]["lemma"],
                              f"{b.get('sp')} {b.get('vs')} {b.get('vt')} {b.get('ps')} {b.get('gn')} {b.get('nu')} {b.get('lex')}"))
        L += table(["Reason", "Ref", "Word", "OSHB morph", "OSHB lemma", "BHSA sp vs vt ps gn nu lex"], srows) + [""]

    # M4, M5
    def m4_m5(self):
        verbs = [(t, vpart(t)) for t in self.toks if vpart(t)]
        self.verbs = verbs
        n = len(verbs)
        conj = collections.Counter(p["morph"][2] for _, p in verbs)
        stem = collections.Counter(p["morph"][1] for _, p in verbs)
        self.wclass = {lem: weak_class(lx) for lem, lx in self.lex.items()}
        wc = collections.Counter(self.wclass.get(p["lemma"], "other") for _, p in verbs)
        qal = [(t, p) for t, p in verbs if p["morph"][1] == "q"]
        qwc = collections.Counter(self.wclass.get(p["lemma"], "other") for _, p in qal)
        strict = qwc["strong"]
        loose = qwc["strong"] + qwc["guttural"]
        self.summary["M4"] = {"verb_tokens": n, "conj": dict(conj), "stem": dict(stem), "weak_class": dict(wc),
                              "qal_weak_class": dict(qwc), "qal_strong_strict_share_of_verbs": strict / n,
                              "qal_strong_incl_gutturals_share_of_verbs": loose / n}
        L = self.md
        L += ["## M4. Verb statistics", "",
              f"{n:,} verb tokens ({pct(n / len(self.toks))} of word tokens). Root class comes from the "
              "BHSA lexeme each OSHB verb lemma aligns to.", ""]
        L += table(["Conjugation", "Tokens", "Share"], [(CONJ[k], f"{v:,}", pct(v / n)) for k, v in conj.most_common()])
        L += [""] + table(["Stem", "Tokens", "Share"], [(STEM.get(k, k), f"{v:,}", pct(v / n)) for k, v in stem.most_common(10)])
        L += ["", "Weak class (primary; priority III-he > hollow > I-nun > I-yod/waw > I-alef > III-alef > "
              "geminate > guttural > strong):", ""]
        L += table(["Class", "All verbs", "Share", "Qal only", "Share of all verbs"],
                   [(k, f"{wc[k]:,}", pct(wc[k] / n), f"{qwc[k]:,}", pct(qwc[k] / n)) for k, _ in wc.most_common()])
        L += ["", f"**Qal strong share of all verb tokens: {pct(strict / n)}** (no weak or guttural root "
              f"letter); {pct(loose / n)} if gutturals count as strong. Lane's earlier figure: about 4%.", ""]
        # M5
        ls = collections.Counter((p["lemma"], p["morph"][1]) for _, p in verbs)
        big = [(lem, s, c) for (lem, s), c in ls.items() if c >= 20]
        per = collections.Counter(lem for lem, _, _ in big)
        multi = sorted([x for x in big if per[x[0]] >= 2], key=lambda x: (-self.cnt[x[0]], x[0], -x[2]))
        self.summary["M5"] = {"pairs_ge20": len(big), "lemmas_with_2plus_stems_ge20": len(per) - list(per.values()).count(1),
                              "non_qal_pairs_ge20": sum(1 for x in big if x[1] != "q")}
        js = [{"lemma": lem, "stem": STEM.get(s, s), "count": c, "lemma_total": self.cnt[lem],
               "gloss_hint": self.gloss(lem)} for lem, s, c in sorted(big, key=lambda x: -x[2])]
        self.dump("lemma_stem.json", js)
        L += ["## M5. Lemma + stem", "",
              f"{len(big)} lemma+stem pairs have >= 20 tokens ({self.summary['M5']['non_qal_pairs_ge20']} non-Qal). "
              f"{self.summary['M5']['lemmas_with_2plus_stems_ge20']} lemmas have two or more such stems; these are "
              "the candidates for separate lemma+stem cards (SPEC Q6; a distinct meaning is judged in Phase 3):", ""]
        L += table(["Lemma", "Stem", "Tokens", "Lemma total"],
                   [(self.lemma_label(lem), STEM.get(s, s), c, self.cnt[lem]) for lem, s, c in multi]) + [""]

    # M6, M7, M9
    def m6_m7_m9(self):
        forms = {}
        for t, p in self.verbs:
            k = fkey(t)
            f = forms.get(k)
            if f is None:
                f = forms[k] = {"key": k, "count": 0, "ex": None, "conj": p["morph"][2], "lemma": p["lemma"]}
            f["count"] += 1
            if f["ex"] is None and t["id"] not in self.quarantined:
                f["ex"] = t
        order = sorted(forms.values(), key=lambda f: -f["count"])
        nv = len(self.verbs)
        self.form_rank = {f["key"]: i + 1 for i, f in enumerate(order)}
        self.known14 = {f["key"] for f in order[:14]}
        # M9a over all tokens
        parses = collections.defaultdict(collections.Counter)
        for t in self.toks:
            parses[STRIP.sub("", t["surface"])][(t["lemma"], t["morph"])] += 1
        amb = {s: c for s, c in parses.items() if len(c) > 1}
        rows = []
        for i, f in enumerate(order[:400]):
            ex = f["ex"] or next(t for t, _ in self.verbs if fkey(t) == f["key"])
            rows.append({"rank": i + 1, "count": f["count"], "translit": self.tr(ex), "lemma": f["lemma"],
                         "morph": f["key"][2], "family": FAMILY[f["conj"]], "parse": parse_label(f["key"][2]),
                         "example_id": ex["id"], "example_ref": ex["ref"], "ambiguous": f["key"][0] in amb,
                         "example_quarantined": f["ex"] is None})
        self.dump("verb_forms_top400.json", rows)
        cum = {}
        acc = 0
        for i, f in enumerate(order):
            acc += f["count"]
            if i + 1 in (100, 200, 300, 400):
                cum[i + 1] = acc / nv
        need = {}
        acc = 0
        for i, f in enumerate(order):
            acc += f["count"]
            for g in (0.5, 0.75, 0.9):
                if g not in need and acc / nv >= g:
                    need[g] = i + 1
        fam300 = collections.Counter(FAMILY[f["conj"]] for f in order[:300])
        fam400 = collections.Counter(FAMILY[f["conj"]] for f in order[:400])
        self.summary["M6"] = {"distinct_forms": len(order), "verb_tokens": nv,
                              "family_top300": dict(fam300), "family_top400": dict(fam400)}
        self.summary["M7"] = {"cum": cum, "forms_needed": {str(k): v for k, v in need.items()}}
        L = self.md
        L += ["## M6. Inflected verb forms", "",
              f"{len(order):,} distinct forms (pointed word without accents or meteg, plus lemma and full "
              f"parse; prefixes and suffixes are part of the form) over {nv:,} verb tokens. Pausal and "
              "contextual spellings, and conjunctive-dagesh variants (lemor / llemor), count as separate forms. Full top 400: `data/measures/verb_forms_top400.json`.", ""]
        budget = {"wayyiqtol": "55 (Unit 3)", "qatal/weqatal": "45 (Unit 4)", "yiqtol/volitive": "45 (Unit 5)",
                  "participle": "35 with inf. (Unit 6)", "infinitive": "(in Unit 6's 35)"}
        L += table(["Family", "In top 300", "In top 400", "Spec budget"],
                   [(k, fam300[k], fam400[k], budget.get(k, "")) for k in
                    ("wayyiqtol", "qatal/weqatal", "yiqtol/volitive", "participle", "infinitive")])
        L += ["", "Spec budgets: Unit 1 = top 8, Unit 2 = next 6 (any family); Units 7-10 take another 106 "
              "from any family. Participles and infinitives share Unit 6's 35.", "", "Top 60:", ""]
        L += table(["#", "Form", "Parse", "Lemma", "Count", "Example", "Ambiguous"],
                   [(r["rank"], r["translit"], r["parse"], self.lemma_label(r["lemma"]), r["count"], r["example_ref"],
                     "yes" if r["ambiguous"] else "") for r in rows[:60]]) + [""]
        L += ["## M7. Verb-token coverage by top forms", ""]
        L += table(["Top N forms", "Share of verb tokens"], [(k, pct(v)) for k, v in cum.items()])
        L += ["", "Forms needed: " + ", ".join(f"{int(k * 100)}% at {v}" for k, v in need.items()) + ".", ""]
        # M9
        amb_tok = sum(sum(c.values()) for c in amb.values())
        vamb = {s: c for s, c in amb.items() if any(m.split("/")[-1][:1] == "V" or "/V" in m or m[1:2] == "V" for _, m in c)}
        top = sorted(amb.items(), key=lambda x: -sum(x[1].values()))[:25]
        self.dump("ambiguous_surfaces.json", [{"surface_key": s, "parses": [{"lemma": a, "morph": b, "count": n}
                                                                           for (a, b), n in c.most_common()]}
                                              for s, c in sorted(amb.items(), key=lambda x: -sum(x[1].values()))])
        mamb = {s: c for s, c in amb.items() if len({m for _, m in c}) > 1}
        mtok = sum(sum(c.values()) for c in mamb.values())
        self.summary["M9a"] = {"surfaces": len(amb), "tokens": amb_tok, "verb_surfaces": len(vamb),
                               "morph_differs_surfaces": len(mamb), "morph_differs_tokens": mtok}
        byid = {}
        for t in self.toks:
            byid.setdefault(STRIP.sub("", t["surface"]), t)
        L += ["## M9a. Surface forms with more than one attested parse", "",
              f"{len(amb):,} surface forms ({len(vamb):,} involving a verb parse) covering {amb_tok:,} tokens "
              f"({pct(amb_tok / len(self.toks))}). These are shown only in their verse and graded against the "
              f"token's own tag (trust rule 5). Lemma-homograph splits count as different parses; {len(mamb):,} "
              f"forms ({mtok:,} tokens) differ in the morphology itself. "
              "Full list: `data/measures/ambiguous_surfaces.json`.", "", "Top 25 by tokens:", ""]
        L += table(["Form", "Tokens", "Parses (count)"],
                   [(self.tr(byid[s]), sum(c.values()),
                     "; ".join(f"{parse_label(m) if '/V' in m or m[1:2] == 'V' else m} {self.lemma_label(a).split(' ')[0]} ({n})"
                               for (a, m), n in c.most_common(4)))
                    for s, c in top]) + [""]
        # M9b
        pool = collections.defaultdict(list)
        for f in order[400:]:
            w = self.wclass.get(f["lemma"], "other")
            if w in ("strong", "guttural", "other") or f["ex"] is None:
                continue
            pool[w].append({"translit": self.tr(f["ex"]), "lemma": f["lemma"], "morph": f["key"][2],
                            "count": f["count"], "example_id": f["ex"]["id"], "example_ref": f["ex"]["ref"],
                            "ambiguous": f["key"][0] in amb})
        self.dump("unseen_weak_pool.json", pool)
        self.summary["M9b"] = {k: {"forms": len(v), "tokens": sum(x["count"] for x in v)} for k, v in pool.items()}
        L += ["## M9b. Unseen weak-verb pool (forms outside the top 400)", "",
              "Root-recovery test pool for Unit 7 (`data/measures/unseen_weak_pool.json`). Quarantined-only "
              "forms are dropped.", ""]
        L += table(["Weak class", "Forms", "Tokens", "Unambiguous forms", "Examples"],
                   [(k, len(v), sum(x["count"] for x in v), sum(1 for x in v if not x["ambiguous"]),
                     ", ".join(x["translit"] for x in v[:4])) for k, v in sorted(pool.items(), key=lambda x: -len(x[1]))]) + [""]

    # M8
    def verses(self):
        vs = collections.OrderedDict()
        for t in self.toks:
            vs.setdefault((t["book"], t["ch"], t["v"]), []).append(t)
        return vs

    def segments(self, levels):
        for key, ts in self.verses().items():
            cur = []
            for i, t in enumerate(ts):
                cur.append(t)
                if i == len(ts) - 1 or set(t["accents"]) & levels:
                    yield key, cur
                    cur = []

    def pool_phrases(self, maxrank, lo, hi, levels):
        out, seen = [], collections.Counter()
        for key, seg in self.segments(levels):
            if not lo <= len(seg) <= hi or any(t["id"] in self.quarantined for t in seg):
                continue
            if all(r <= maxrank for t in seg for r in t["_r"]):
                k = tuple(STRIP.sub("", t["surface"]) for t in seg)
                seen[k] += 1
                if seen[k] == 1:
                    out.append({"ref": seg[0]["ref"], "start": seg[0]["pos"], "end": seg[-1]["pos"],
                                "words": len(seg), "text": self.phrase(seg), "_k": k})
        for x in out:
            x["occurrences"] = seen[x.pop("_k")]
        return out

    def verbs_ok(self, ts, conjs):
        for t in ts:
            p = vpart(t)
            if p and p["morph"][2] not in conjs and fkey(t) not in self.known14:
                return False
        return True

    def m8(self):
        L = self.md
        L += ["## M8. Micro-reading pools", "",
              "Phrases split at king-level disjunctive accents (atnach, segolta, shalshelet, zaqef, tifcha, "
              "verse end). Names, prefixes and suffixes always allowed. Repeated identical phrases count once "
              "(occurrences kept). Units with quarantined tokens are skipped. Full pools: "
              "`data/measures/micro_pools.json`.", ""]
        pools, rows = {}, []
        for name, rank, lo, hi in (("M8a", 50, 2, 6), ("M8b", 120, 2, 8)):
            p = self.pool_phrases(rank, lo, hi, KINGS)
            alt = self.pool_phrases(rank, lo, hi, KINGS | DUKES)
            pools[name] = p
            rows.append((name, f"rank <= {rank}, {lo}-{hi} words", len(p), len(alt),
                         statistics.median([x["words"] for x in p]) if p else "-"))
        # M8c: verses
        vs = self.verses()
        for name, rank, conjs, need in (("M8c-wayyiqtol", 190, {"w"}, {"w"}), ("M8c-qatal", 260, {"w", "p", "q"}, {"p", "q"})):
            res = []
            for key, ts in vs.items():
                if len(ts) < 3 or any(t["id"] in self.quarantined for t in ts):
                    continue
                if not self.verbs_ok(ts, conjs) or sum(t["_name"] for t in ts) > 0.3 * len(ts):
                    continue
                if not any(vpart(t) and vpart(t)["morph"][2] in need for t in ts):
                    continue
                c = self.lemma_cov(ts, rank)
                if c >= 0.9:
                    res.append({"ref": ts[0]["ref"], "words": len(ts), "coverage": round(c, 3),
                                "text": self.phrase(ts)})
            pools[name] = res
            rows.append((name, f"verses with a {'/'.join(sorted(need))} verb; other verbs {'/'.join(sorted(conjs))} or "
                               f"top-14 forms; names <= 30%; >= 90% at {rank}",
                         len(res), "", statistics.median([x["words"] for x in res]) if res else "-"))
        # M8d: 3-5 verse dialogue windows
        keys = list(vs.keys())
        cand = []
        conjs = set("wpqijhv")
        for i in range(len(keys)):
            for w in (3, 4, 5):
                ks = keys[i:i + w]
                if len(ks) < w or len({k[:2] for k in ks}) > 1 or ks[-1][2] - ks[0][2] != w - 1:
                    continue
                ts = [t for k in ks for t in vs[k]]
                if any(t["id"] in self.quarantined for t in ts) or not self.verbs_ok(ts, conjs):
                    continue
                fin = [vpart(t)["morph"] for t in ts if vpart(t) and vpart(t)["morph"][2] in FINITE]
                speech = [m for m in fin if m[2] in "ijhv" or (m[2] in "pq" and m[3] in "12") or (m[2] == "w" and m[3] == "1")]
                if len(speech) < 3 or len(speech) < 0.5 * len(fin):
                    continue
                c = self.lemma_cov(ts, 330)
                if c >= 0.9:
                    cand.append((c, w, ks, ts))
        cand.sort(key=lambda x: (-x[0], -x[1]))
        used, picked = set(), []
        for c, w, ks, ts in cand:
            if used & set(ks):
                continue
            used |= set(ks)
            picked.append({"ref": ts[0]["ref"], "verses": w, "words": len(ts), "coverage": round(c, 3),
                           "text": self.phrase(ts)})
        picked.sort(key=lambda x: (corpus.load_config()["books"].index(x["ref"].split(".")[0]),
                                   int(x["ref"].split(".")[1]), int(x["ref"].split(".")[2])))
        pools["M8d"] = picked
        rows.append(("M8d", "3-5 verses, >= 50% speech verbs, no ptc/inf beyond top 14, >= 90% at 330",
                     f"{len(picked)} (non-overlapping; {len(cand)} windows)", "", statistics.median([x["words"] for x in picked]) if picked else "-"))
        self.dump("micro_pools.json", pools)
        self.summary["M8"] = {k: len(v) for k, v in pools.items()}
        L += table(["Pool", "Rule", "Items", "Items if duke-level accents also split", "Median words"], rows)
        for k, v in pools.items():
            if not v:
                continue
            ex = sorted(v, key=lambda x: -x.get("occurrences", 1))[:6] if k in ("M8a", "M8b") else v[:: max(1, len(v) // 6)][:6]
            L += ["", f"{k} samples:", ""]
            L += [f"- {x['ref']}: {x['text']}" + (f" (x{x['occurrences']})" if x.get("occurrences", 1) > 1 else "") for x in ex]
        L += [""]

    # M10
    def m10(self):
        ts = [t for t in self.toks if t["book"] == "Exod" and t["ch"] in (3, 14)]
        cc = collections.Counter(p["lemma"] for t in ts for p in t["parts"] if pclass(p) == "vocab")
        off = sorted([x for x in cc if self.rank[x] > CORE], key=lambda x: self.rank[x])
        nm = collections.Counter(p["lemma"] for t in ts for p in t["parts"] if pclass(p) == "name")
        top300 = {k for k, r in self.form_rank.items() if r <= 300}
        fb = {}
        for t in ts:
            if vpart(t) and fkey(t) not in top300:
                fb.setdefault(fkey(t), []).append(t)
        a = [{"lemma": x, "rank": self.rank[x], "corpus_count": self.cnt[x], "in_chapters": cc[x],
              "gloss_hint": self.gloss(x)} for x in off]
        b = [{"translit": self.tr(v[0]), "ref": v[0]["ref"], "lemma": k[1], "morph": k[2], "parse": parse_label(k[2]),
              "in_chapters": len(v), "corpus_rank": self.form_rank[k]} for k, v in sorted(fb.items(), key=lambda kv: kv[1][0]["ref"])]
        self.dump("exodus_topup.json", {"M10a": a, "M10b": b, "names": [{"lemma": x, "count": c, "gloss_hint": self.gloss(x)}
                                                                       for x, c in nm.most_common()]})
        self.summary["M10"] = {"lemmas_over_750": len(a), "tokens_over_750": sum(cc[x] for x in off),
                               "forms_outside_top300": len(b), "names": len(nm)}
        L = self.md
        L += ["## M10. Exodus 3 and 14 top-up", "",
              f"(a) {len(a)} lemmas in Exod 3 and 14 have rank > {CORE} ({sum(cc[x] for x in off)} tokens); "
              f"spec budget 80. (b) {len(b)} distinct verb forms there are outside the top 300; spec budget 30. "
              f"Names in the two chapters: {len(nm)}. Full lists: `data/measures/exodus_topup.json`.", ""]
        L += table(["Lemma", "Rank", "Corpus count", "In Exod 3/14"],
                   [(self.lemma_label(x["lemma"]), x["rank"], x["corpus_count"], x["in_chapters"]) for x in a]) + [""]
        L += ["(b) forms:", ""]
        L += table(["Form", "Ref", "Parse", "Corpus form rank"],
                   [(x["translit"], x["ref"], x["parse"], x["corpus_rank"]) for x in b]) + [""]

    # M11
    def m11(self):
        rows, js = [], []
        for label, book, a, z in PASSAGES:
            ts = [t for t in self.toks if in_span(t, book, a, z)]
            off = {p["lemma"] for t in ts for p in t["parts"] if pclass(p) == "vocab" and self.rank[p["lemma"]] > CORE}
            covs = [self.lemma_cov(ts, n) for n in PASSAGE_RANKS]
            nm = sum(1 for t in ts if t["_name"]) / len(ts)
            rows.append([label, len(ts)] + [pct(c) for c in covs] + [len(off), pct(nm)])
            js.append({"passage": label, "tokens": len(ts), "coverage": dict(zip(PASSAGE_RANKS, covs)),
                       "off_list_lemmas": len(off), "name_token_share": nm})
        chap = collections.OrderedDict()
        for t in self.toks:
            chap.setdefault((t["book"], t["ch"]), []).append(t)
        best = sorted(((self.lemma_cov(ts, 400), k, ts) for k, ts in chap.items() if len(ts) >= 150),
                      key=lambda x: -x[0])[:20]
        self.dump("passages.json", {"passages": js, "top_chapters_400": [
            {"chapter": f"{k[0]} {k[1]}", "tokens": len(ts), "coverage_400": c,
             "name_token_share": sum(1 for t in ts if t["_name"]) / len(ts)} for c, k, ts in best]})
        self.summary["M11"] = js
        L = self.md
        L += ["## M11. Candidate passages", "", "Lemma coverage (a) at each rank; off-list = distinct lemmas "
              f"ranked > {CORE}.", ""]
        L += table(["Passage", "Tokens"] + [f"@{n}" for n in PASSAGE_RANKS] + ["Off-list", "Name tokens"], rows)
        L += ["", "20 chapters with the highest coverage at rank 400 (chapters with >= 150 tokens). Lists and "
              "genealogies score high because names are outside the denominator:", ""]
        L += table(["Chapter", "Tokens", "@400", "Name tokens"],
                   [(f"{k[0]} {k[1]}", len(ts), pct(c), pct(sum(1 for t in ts if t["_name"]) / len(ts)))
                    for c, k, ts in best]) + [""]

    def poems(self):
        rows = []
        for b, c1, v1, c2, v2 in POEM_CANDIDATES:
            n = sum(1 for t in self.toks if in_span(t, b, (c1, v1), (c2, v2)))
            rows.append((f"{b} {c1}:{v1}" + (f"-{v2}" if (c1, v1) != (c2, v2) else ""), n))
        self.summary["poem_candidates"] = dict(rows)
        self.md += ["## Poem bounds (SPEC 0.1)", "",
                    "The configured poem spans all have tokens (verify_corpus). 2 Sam 1:19-27 and 2 Kgs 19:21-28 "
                    "were added after Phase 2. Short verse-poems kept in the corpus (Lane, 2026-10-08):", ""]
        self.md += table(["Span", "Tokens"], rows)
        self.md += ["", f"Total {sum(n for _, n in rows)} tokens ({pct(sum(n for _, n in rows) / len(self.toks))} of the corpus).", ""]

    def dump(self, name, obj):
        os.makedirs(OUT, exist_ok=True)
        with open(os.path.join(OUT, name), "w", encoding="utf-8", newline="\n") as f:
            json.dump(obj, f, ensure_ascii=False, indent=1)

    def run(self):
        self.summary = {}
        steps = [("M1", self.m1), ("cov", self.prep_cov), ("M2", self.m2), ("M3", self.m3), ("M13", self.m13),
                 ("M4-5", self.m4_m5), ("M6-7-9", self.m6_m7_m9), ("M8", self.m8), ("M10", self.m10),
                 ("M11", self.m11), ("poems", self.poems)]
        sections = {}
        for name, fn in steps:
            t0 = time.time()
            start = len(self.md)
            fn()
            sections[name] = self.md[start:]
            self.timing[name] = time.time() - t0
        order = ["M1", "M2", "M3", "M4-5", "M6-7-9", "M8", "M10", "M11", "M13", "poems"]
        body = [x for k in order for x in sections.get(k, [])]
        self.dump("lemma_ranks.json", self.lemma_rows)
        self.dump("names.json", self.name_rows)
        self.dump("summary.json", self.summary)
        with open(QUAR, "w", encoding="utf-8", newline="\n") as f:
            json.dump(self.quarantine, f, ensure_ascii=False, indent=1)
        head = "# Measures (Phase 2)\n\n" + MARKER + "\n"
        if os.path.exists(MD):
            old = open(MD, encoding="utf-8").read()
            if MARKER in old:
                head = old.split(MARKER)[0] + MARKER + "\n"
        with open(MD, "w", encoding="utf-8", newline="\n") as f:
            f.write(head + "\n" + "\n".join(body) + "\n")
        print("timing:", {k: round(v, 1) for k, v in self.timing.items()})


if __name__ == "__main__":
    Run().run()
