/**
 * Learn tab: short grammar lessons, read at your own pace.
 *
 * Not an SRS deck and not gated behind completion -- same philosophy as the
 * Read tab (CLAUDE.md: no streaks, no guilt mechanics). Every lesson is
 * always available; there's no "progress" tracked here to feel behind on.
 * This is reference/explanatory reading that backs up what Vocab and Parse
 * already drill by pattern-recognition -- the rule behind the pattern.
 *
 * Takes an array of lesson-group JSON objects (main.js's LESSON_GROUPS,
 * one file per group -- group 1 is prefixes/suffixes, group 2 is construct
 * chains). The list view sections lessons by group; the detail view finds
 * a lesson by id across all groups, since ids are unique project-wide.
 *
 * Two example shapes coexist, both generated by their pipeline script from
 * real Jonah text, never a word invented to illustrate a rule:
 *   - single-word (every group-1 example, and group 2's "shrinks"/
 *     "special-endings" lessons): one word, decomposed into whatever
 *     prefix/base/suffix it actually has, with `highlight` naming which
 *     span to pick out in accent color.
 *   - chain (group 2's construct chains; group 4's adjective-agreement
 *     pairs; group 5's word-order and verbless-clause examples): a
 *     `tokens` array, one entry per printed word in the phrase (these are
 *     separate words, not one word's internal prefix/suffix), each tagged
 *     with its own `role` instead of a highlight span, plus a
 *     hand-authored `phrase_gloss` since a word-by-word join can't
 *     produce an idiomatic "word of the LORD". role is "construct"/
 *     "absolute" for a real construct chain (one word leans on the
 *     other); everywhere else it's "plain" (the words are just read in
 *     sequence, so neither gets picked out in accent or dimmed).
 *
 * For any word (single-word example or chain token) whose actual shape
 * differs from its own dictionary citation form, a small comparison line
 * is shown -- this falls directly out of data already present on every
 * example (lemma_citation_form/lemma_transliteration), no per-lesson flag
 * needed to turn it on.
 *
 * Hard rule 1 applies here same as every other view: not one Hebrew
 * character appears in this file. Every glyph is read from
 * data/lessons_group*.json at runtime.
 */

let selectedId = null;

export function render(root, groups) {
  root.textContent = '';

  if (selectedId) {
    for (const g of groups) {
      const lesson = g.lessons.find((l) => l.id === selectedId);
      if (lesson) {
        root.appendChild(lessonDetail(lesson));
        return;
      }
    }
    selectedId = null; // stale id (shouldn't happen) -- fall through to the list
  }

  root.appendChild(lessonList(groups));
}

function lessonList(groups) {
  const wrap = document.createDocumentFragment();

  const h = document.createElement('h1');
  h.className = 'title';
  h.textContent = 'Learn';
  wrap.appendChild(h);

  const note = document.createElement('p');
  note.className = 'note';
  note.textContent = 'The grammar behind the patterns Vocab, Parse, and Read already have you recognizing -- illustrated throughout with real words from the actual text.';
  wrap.appendChild(note);

  for (const g of groups) {
    const heading = document.createElement('p');
    heading.className = 'row-label';
    heading.style.margin = '0 0 8px';
    heading.textContent = g.metadata.group_title;
    wrap.appendChild(heading);

    const box = document.createElement('div');
    box.className = 'group';
    const sorted = [...g.lessons].sort((a, b) => a.order - b.order);
    for (const lesson of sorted) {
      const b = document.createElement('button');
      b.className = 'btn';
      b.appendChild(document.createTextNode(lesson.title));
      const count = document.createElement('span');
      count.className = 'row-sub';
      count.textContent = `  ${lesson.examples.length} example${lesson.examples.length === 1 ? '' : 's'}`;
      b.appendChild(count);
      b.addEventListener('click', () => { selectedId = lesson.id; rerender(); });
      box.appendChild(b);
    }
    wrap.appendChild(box);
  }

  return wrap;
}

function lessonDetail(lesson) {
  const wrap = document.createDocumentFragment();

  const back = document.createElement('button');
  back.className = 'btn lesson-back';
  back.textContent = '← Learn';
  back.addEventListener('click', () => { selectedId = null; rerender(); });
  wrap.appendChild(back);

  const h = document.createElement('h1');
  h.className = 'title';
  h.textContent = lesson.title;
  wrap.appendChild(h);

  for (const para of lesson.paragraphs) {
    const p = document.createElement('p');
    p.className = 'lesson-p';
    p.textContent = para;
    wrap.appendChild(p);
  }

  for (const ex of lesson.examples) {
    wrap.appendChild(ex.tokens ? chainExampleCard(ex) : wordExampleCard(ex));
  }

  return wrap;
}

function wordExampleCard(ex) {
  const card = document.createElement('div');
  card.className = 'lesson-example';

  const heb = document.createElement('p');
  heb.className = 'lesson-example-heb heb';
  heb.lang = 'he';
  appendSpan(heb, ex.prefix_form, ex.highlight === 'prefix');
  appendSpan(heb, ex.base_form, ex.highlight === 'base');
  appendSpan(heb, ex.suffix_form, ex.highlight === 'suffix');
  card.appendChild(heb);

  const t = document.createElement('p');
  t.className = 'card-translit';
  t.textContent = ex.transliteration;
  card.appendChild(t);

  const cf = citationLine(ex);
  if (cf) card.appendChild(cf);

  const glossParts = [];
  if (ex.prefix_morphemes && ex.prefix_morphemes.length) {
    glossParts.push(ex.prefix_morphemes.map((m) => m.gloss).join(' + '));
  }
  glossParts.push(ex.gloss);
  const g = document.createElement('p');
  g.className = 'lesson-example-gloss';
  g.textContent = glossParts.join(' + ');
  card.appendChild(g);

  card.appendChild(noteLine(ex.note));
  card.appendChild(refLine(ex.ref));

  return card;
}

function chainExampleCard(ex) {
  const card = document.createElement('div');
  card.className = 'lesson-example';

  const heb = document.createElement('p');
  heb.className = 'lesson-example-heb heb';
  heb.lang = 'he';
  ex.tokens.forEach((tok, i) => {
    if (i > 0) heb.appendChild(document.createTextNode(' '));
    // "plain" (word-order/verbless-clause/agreement phrases) gets no
    // accent/dim split -- neither word leans on the other the way a
    // construct chain's construct/absolute pair does.
    if (tok.role === 'plain') {
      heb.appendChild(document.createTextNode(tok.surface_form));
      return;
    }
    const span = document.createElement('span');
    span.className = tok.role === 'construct' ? 'card-heb-verb' : 'card-heb-affix';
    span.textContent = tok.surface_form;
    heb.appendChild(span);
  });
  card.appendChild(heb);

  const t = document.createElement('p');
  t.className = 'card-translit';
  t.textContent = ex.tokens.map((tok) => tok.transliteration).join(' ');
  card.appendChild(t);

  const g = document.createElement('p');
  g.className = 'lesson-example-gloss';
  g.textContent = ex.phrase_gloss;
  card.appendChild(g);

  card.appendChild(noteLine(ex.note));
  card.appendChild(refLine(ex.ref));

  return card;
}

function citationLine(word) {
  if (!word.lemma_citation_form || word.lemma_citation_form === word.base_form) return null;
  const p = document.createElement('p');
  p.className = 'lesson-example-citation';
  const heb = document.createElement('span');
  heb.className = 'heb';
  heb.lang = 'he';
  heb.textContent = word.lemma_citation_form;
  p.appendChild(document.createTextNode('dictionary form: '));
  p.appendChild(heb);
  p.appendChild(document.createTextNode(` (${word.lemma_transliteration})`));
  return p;
}

function noteLine(text) {
  const note = document.createElement('p');
  note.className = 'lesson-example-note';
  note.textContent = text;
  return note;
}

function refLine(ref) {
  const p = document.createElement('p');
  p.className = 'lesson-example-ref';
  p.textContent = ref;
  return p;
}

function appendSpan(parent, text, isFocus) {
  if (!text) return;
  const span = document.createElement('span');
  span.className = isFocus ? 'card-heb-verb' : 'card-heb-affix';
  span.textContent = text;
  parent.appendChild(span);
}

let rerender = () => {};
export function setRerender(fn) { rerender = fn; }
